#!/usr/bin/env ruby
#^syntax detection

# Install Cookbooks by typing `librarian-chef install`

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential', '1.4.2'
cookbook 'imagemagick', '0.2.2'
cookbook 'java', '1.15.4'
cookbook 'database', '1.5.2'
cookbook 'nodejs', '1.3.0'
cookbook 'php', '1.2.6'

# Custom cookbooks
cookbook "main",
         :path => "vendor/cookbooks/main"


# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
